version: "3.8"

services:
  # db:
  #   image: mysql:8.0
  #   volumes:
  #     - mysql_data:/var/lib/mysql
  #   ports:
  #     - "3306:3306"
  #   env_file:
  #     - .env

  api:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/code
    ports:
      - "8001:8000"
    # depends_on:
    #   - db
    env_file:
      - .env
# volumes:
#   mysql_data:
