# Generated by Django 5.0.3 on 2024-10-14 23:18

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicles', '0004_rename_type_typevehicle_vehicle_license_plate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(default='', max_length=500)),
                ('file', models.FileField(null=True, upload_to='')),
                ('value', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('date', models.DateField(default=datetime.date.today)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='vehicles.vehicle')),
                ('type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='expenses.typeexpense')),
            ],
        ),
    ]
