# Generated by Django 5.0.3 on 2024-05-17 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0003_vehicleimage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Type',
            new_name='TypeVehicle',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='license_plate',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='year',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
