# Generated by Django 5.0.3 on 2024-11-04 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0004_rename_type_typevehicle_vehicle_license_plate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='state',
            field=models.CharField(default='', max_length=2),
        ),
    ]
